name: Execução de testes na pipeline

on:
  [push]

jobs:
  cypress-run:
    run-on: ubuntu-latest

    steps:
      - name: checkout projeto
        uses: actions/checkout@v2
      
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start